### ISSUE TITLE
Add test to the repository check that the website successfully builds.

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/mimic_wfdb_tutorials#10]
It would be good to add a test to the repository that confirms that updates to the code don't break the website build. This test could be automatically run against the repo using github workflows.

**Comment by peterhcharlton** [comment]
Agreed. I haven't used tests on GitHub before, but will look into it.

**Comment by peterhcharlton** [comment]
Thanks very much - I think this is now done.
