### ISSUE TITLE
Requirements.txt folder should be in root of project

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/mimic_wfdb_tutorials#13]
The following change broke the tests: https://github.com/MIT-LCP/mimic_wfdb_tutorials/commit/38d7b4fda4940abbf0edd987dd2d2e6d736601f9

It is usual for the requirements.txt file to live in the root of the project, so it might be worth undoing this change (`git revert 38d7b4fda4940abbf0edd987dd2d2e6d736601f9`) unless there is a reason to move it.

**Comment by peterhcharlton** [comment]
Thanks - that's now been corrected.
