### ISSUE TITLE
Organise top level files into subfolders

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/mimic_wfdb_tutorials#5]
Currently there are a lot of files in the root of the repository. If possible, it would be good to try to organise the content into subfolders to make it easier to navigate content. e.g. perhaps:

- `images` folder for images
- `data` folder for datasets
- `content` folder or similar for markdown

**Comment by peterhcharlton** [comment]
I agree - I'll have a go at this.

**Comment by tompollard** [comment]
This should at least partially be addressed in https://github.com/MIT-LCP/mimic_wfdb_tutorials/pull/9

**Comment by peterhcharlton** [comment]
I think we've had a good go at addressing this. I haven't been able to keep the notebooks in the root folder whilst getting the jupyter book to build. Therefore, I've created a [notebooks folder](/tree/master/content/tutorial/notebooks) which currently contains the notebooks. I wasn't able to get it to recognise the paths of the notebooks when they were in the root folder (the paths are specified in the [_toc.yml](/blob/master/content/_toc.yml) file). We could revisit this another time and put the notebooks in the root folder if we can solve this issue.

**Comment by tompollard** [comment]
> I think we've had a good go at addressing this. I haven't been able to keep the notebooks in the root folder whilst getting the jupyter book to build. Therefore, I've created a [notebooks folder](https://github.com/MIT-LCP/mimic_wfdb_tutorials/tree/master/content/tutorial/notebooks) which currently contains the notebooks. I wasn't able to get it to recognise the paths of the notebooks when they were in the root folder (the paths are specified in the [_toc.yml](https://github.com/MIT-LCP/mimic_wfdb_tutorials/blob/master/content/_toc.yml) file). We could revisit this another time and put the notebooks in the root folder if we can solve this issue.

This sounds good, thanks!
