### ISSUE TITLE
Add guidance for building/serving the repo locally

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/mimic_wfdb_tutorials#6]
To make it easier to develop the repo, it would be helpful to outline the steps necessary to serve the files locally. This guidance could be added to the readme.

**Comment by peterhcharlton** [comment]
I agree. Currently there is guidance in [the maintenance section of the book](/about-maintenance). I agree, it would probably be better to put this in the readme, and I expect that the guidance could be improved.

**Comment by tompollard** [comment]
thanks pete!
